name: Proxy Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  scanner:
    runs-on: ubuntu-latest
    concurrency:
      group: proxy-scan

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure git
      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      # Setup Bun
      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      # Run the scanner script
      - name: Start Scan
        run: |
          bun install
          bun run ./vless/proxyChecker.ts

      # Publish the results
      - name: Publish Result
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9
        with:
          add: './vless/*List.{txt,json}'
          message: "Update proxy list"
          default_author: github-actions
