name: Proxy Checker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "export PATH=$HOME/.bun/bin:$PATH" >> $GITHUB_ENV
          echo "export PATH=$HOME/.bun/bin:$PATH" >> $GITHUB_PATH
          bun --version # Verify Bun installation

      # Run script from the vless directory
      - name: Run Proxy Checker
        run: |
          cd ./vless
          bun proxyChecker.ts

      # Commit and Push Results
      - name: Commit and Push Results
        run: |
          cd ./vless
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kvProxyList.json proxyList.txt
          git commit -m "Update proxy results"
          git push
