name: Proxy Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  scanner:
    runs-on: ubuntu-latest
    concurrency:
      group: proxy-scan

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure Git
      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      # Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo 'export PATH="$HOME/.bun/bin:$PATH"' >> $GITHUB_ENV

      # Run the scanner script
      - name: Start Scan
        run: |
          bun install
          bun run ./vless/proxyChecker.ts
        env:
          PATH: ${{ env.PATH }}

      # Publish the results
      - name: Publish Result
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9
        with:
          add: './vless/*List.{txt,json}'
          message: "Update proxy list"
          default_author: github-actions
