name: Proxy Checker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode sumber dari repositori
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
          echo "PATH=$HOME/.bun/bin:$PATH" >> $GITHUB_ENV
          ~/.bun/bin/bun --version # Verifikasi instalasi Bun

      # Pindah ke folder vless dan jalankan skrip
      - name: Run Proxy Checker
        working-directory: ./vless
        run: |
          export PATH="$HOME/.bun/bin:$PATH"
          ~/.bun/bin/bun proxyChecker.ts

      # Upload hasil file ke repositori
      - name: Commit and Push Results
        working-directory: ./vless
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kvProxyList.json proxyList.txt
          git commit -m "Update proxy results"
          git push
