name: 🌐 Update Proxy IP Status

on:
  # Schedule workflow to run every 3 days at midnight
  schedule:
    - cron: '0 0 */3 * *'

  # Allow manual trigger of the workflow
  workflow_dispatch:

jobs:
  update-proxies:
    runs-on: ubuntu-latest
    name: 🚀 Update Proxy IP Status

    steps:
    # Step 1: Checkout the repository
    - name: 📂 Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: 🐍 Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install Python dependencies
    - name: 📦 Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Step 4: Run the Python script to update proxy status
    - name: 🔄 Update Proxy Status
      env:
        IP_FILE: './cek/file.txt'
        API_URL: 'https://check.installer.us.kg/check?ip={ip}:{port}' # Proxy check API URL
      run: |
        python ./cek/update_proxy_status.py

    # Step 5: Commit and push changes if any
    - name: 📤 Commit and Push Changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"

        # Add changed files to staging
        git add ./cek/*.txt || echo "⚠️ No files to add."

        # Commit and push if there are changes
        if git diff --cached --exit-code; then
          echo "✅ No changes detected, skipping commit."
        else
          git commit -m "🔄 Update proxy IP status" && echo "✅ Changes committed."
          git push && echo "🚀 Changes pushed to repository."
        fi
